# FROM node:10-slim

# USER node

# RUN mkdir -p /home/node/app

# WORKDIR /home/node/app

# COPY --chown=node package*.json ./

# RUN npm install

# COPY --chown=node ./ .

# RUN npm run build

# RUN npm run frontend-dev

# CMD ["npm", "run", "start:prod"]

FROM node:12.14.0-alpine3.11 As development

RUN apk add --no-cache bash

RUN npm config set cache /home/node/app/.npm-cache --global

RUN npm i -g @nestjs/cli@7.4.1

USER node

WORKDIR /home/node/app

COPY package*.json ./

RUN npm install --only=development

COPY . .

ENV ADDR=0.0.0.0

EXPOSE 3000

# Uncomment to run the migrations before running the binary:
# CMD /bin/app migrate; /bin/app
CMD ["npm", "start"]