# Generated by Django 3.0.8 on 2020-07-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AulasMaratona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'aula maratona',
                'verbose_name_plural': 'aulas maratona',
            },
        ),
    ]
